name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t angular-training:latest .
      - name: Push Docker image
        run: |
          docker tag angular-training:latest ${{ env.DOCKER_USERNAME }}/angular-training:latest
          docker push ${{ env.DOCKER_USERNAME }}/angular-training:latest
