name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t angulartraining:latest .
      - name: Push Docker image
        run: |
          docker tag angulartraining:latest ${{ secrets.DOCKERHUB_USERNAME }}/angulartraining:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/angulartraining:latest
