name: Build and Push Docker Image

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USERNAME }}
          password: ${{ secrets.GIT_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t angulartraining:latest .
      - name: Push Docker image
        run: |
          docker tag angulartraining:latest ghcr.io/${{ secrets.GIT_USERNAME }}/angulartraining:latest
          docker push ghcr.io/${{ secrets.GIT_USERNAME }}/angulartraining:latest

  pull:
    needs: build-and-push
    runs-on: self-hosted
    steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                    registry: ghcr.io
                    username: ${{ secrets.GIT_USERNAME }}
                    password: ${{ secrets.GIT_PASSWORD }}

            - name: pull image
              run: |
                docker pull ghcr.io/${{ secrets.GIT_USERNAME }}/angulartraining
            - name: kill container
              run: docker container inspect angular-app &>/dev/null && docker rm -f angular-app
            - name: run image
              run: sudo docker run --rm -d -p 80:80 --name angular-app ghcr.io/${{ secrets.GIT_USERNAME }}/angulartraining
